### ISSUE TITLE
Deep Storage Unit Cart

### ISSUE THREAD

**Issue by Mattabase** [BrassGoggledCoders/MoarCarts#23]
http://pastebin.com/U3REYrmw

Clicked the DSU Cart With High Speed Rails.

**Comment by SkySom** [comment]
@Mattabase Think I got it fixed in this build: [MoarCarts](http://jenkins.k-4u.nl/job/MoarCarts/lastSuccessfulBuild/artifact/build/libs/moarcarts-1.7.10-1.1.1-50.jar) Mind takin' a look for me? Also will need boilerplate from here [Boilerplate](http://jenkins.k-4u.nl/job/Boilerplate/81/artifact/build/libs/boilerplate-1.7.10-6.3.0.81-universal.jar) I'll take a better test in the morning but feel free to test on your end.

**Comment by Mattabase** [comment]
http://pastebin.com/bK2iZ5Sn

With the new version, clicked on the DSU Again.

**Comment by SkySom** [comment]
Ah I had wondered if I would need to do the same for EntityPlayerSP as I did for EntityPlayerMP. Do you use a specific pack or anything? Could use it to test things before I put out to you.

**Comment by Mattabase** [comment]
I am currently working on a modpack, so that is what I am testing in.

**Comment by SkySom** [comment]
Ah! Alright. Well I think the EntityPlayerSP is the last issue it should have (At that point I'll have all versions of EntityPlayer's so it should have casting issues/NPE's at all.

**Comment by SkySom** [comment]
Should have another build late tomorrow ready for you.

**Comment by Mattabase** [comment]
Sweet, thanks.

**Comment by SkySom** [comment]
http://jenkins.k-4u.nl/view/BrassGoggledCoders/job/MoarCarts/51/artifact/build/libs/moarcarts-1.7.10-1.1.1-51.jar 

EntityPlayerSP should no longer be null. Also fixed a bug with some updates in the DSU too.

**Comment by SkySom** [comment]
Fixed in 1.2.2
